PHP=/usr/bin/php
#PHP=/opt/php5/bin/php
all: all_tests


all_tests:
	$(PHP) /usr/local/bin/phpunit  t1.php    # --bootstrap bootstrap.php
	$(PHP) /usr/local/bin/phpunit  t2.php    # --bootstrap bootstrap.php
